import type { SMSAdapter, SendResult } from './types.ts';
import { toPakistaniMsisdn } from './phone.ts';

export { toPakistaniMsisdn };

// DEVELOPMENT ONLY - no SMS is ever sent by this adapter.
//
// Lets developers test the full sign-up/OTP flow before an SMS provider is active:
// the real OTP generated by Supabase Auth is written to this function's logs
// (Supabase Dashboard > Edge Functions > send-sms > Logs) instead of being delivered.
//
// Safeguards:
// - Only used when SMS_PROVIDER=devlog is set explicitly; never the default.
// - Only numbers listed in SMS_DEV_ALLOWED_PHONES (comma-separated) are accepted.
//   Every other number gets an error, so real users are never told a code was sent.
// - Never reports a provider message id; the log states that no SMS was sent.

export class DevLogAdapter implements SMSAdapter {
  name = 'DevLog (development only, no SMS sent)';

  async send(to: string, otp: string): Promise<SendResult> {
    const allowed = (Deno.env.get('SMS_DEV_ALLOWED_PHONES') || '')
      .split(',')
      .map((p) => toPakistaniMsisdn(p.trim()))
      .filter(Boolean);

    if (allowed.length === 0) {
      return {
        success: false,
        error: 'Dev log mode requires SMS_DEV_ALLOWED_PHONES (comma-separated test numbers). No SMS was sent.',
      };
    }

    const recipient = toPakistaniMsisdn(to);
    if (!allowed.includes(recipient)) {
      return {
        success: false,
        error: 'SMS delivery is not active yet (development log mode) and this number is not a registered test number. No SMS was sent.',
      };
    }

    // OTP first so it stays visible when the dashboard truncates long log lines
    console.log(
      `DEV OTP ${otp} for ${recipient.slice(0, 5)}****${recipient.slice(-2)} [Qareeb SMS Hook][DEV LOG MODE] NO SMS WAS SENT`
    );

    return {
      success: true,
      rawResponse: 'devlog: OTP written to function logs, no SMS sent',
    };
  }
}
